apiVersion: v1
kind: Service
metadata:
  name: gestion-etablissement
  namespace: staging
spec:
  selector:
    app: gestion-etablissement
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer 