name: Pipeline CI/CD Simple

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Récupérer le code
      uses: actions/checkout@v3
    
    - name: Configurer Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Vérifier la structure du projet
      run: |
        echo "=== Structure du projet ==="
        ls -la
        echo "=== Contenu du pom.xml ==="
        cat pom.xml
        echo "=== Version de Java ==="
        java -version
        echo "=== Version de Maven ==="
        mvn -version
        
    - name: Compiler avec Maven (verbose)
      run: mvn -B -X clean package -DskipTests
      
    - name: Exécuter les tests
      run: mvn test
      continue-on-error: true

    - name: Construire l'image Docker
      run: |
        docker build -t gestion-etablissement:latest .
        docker images
      continue-on-error: true 